name: Build and Deploy

on:
  push:
    branches: ["main", "test"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          upload_condition: 'true'

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }} # This is a bit brittle, using the branch name as the environment name
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          bucket: ${{ secrets.S3_BUCKET }}
          region: ${{ secrets.S3_BUCKET_REGION}}
          distribution_id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
